spring:
  application:
    name: wms-platform
  datasource:
    url: jdbc:h2:mem:wmsdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

logging:
  level:
    root: INFO
    com.wmsplatform: DEBUG
    org.hibernate.SQL: DEBUG
